import {firebaseConfig,firebaseSdkVersion} from './firebase-config.js';
const sdk=m=>`https://www.gstatic.com/firebasejs/${firebaseSdkVersion}/${m}.js`;
export async function createCloud(handlers={}){
 const [appMod,authMod,fsMod]=await Promise.all([import(sdk('firebase-app')),import(sdk('firebase-auth')),import(sdk('firebase-firestore'))]);
 const app=appMod.initializeApp(firebaseConfig),auth=authMod.getAuth(app),db=fsMod.getFirestore(app);
 await authMod.setPersistence(auth,authMod.browserLocalPersistence);
 const playerRef=uid=>fsMod.doc(db,'v2Players',uid), listingRef=id=>fsMod.doc(db,'v2MarketListings',id);
 async function signGoogle(){return authMod.signInWithPopup(auth,new authMod.GoogleAuthProvider())}
 async function signEmail(email,password,create=false){return create?authMod.createUserWithEmailAndPassword(auth,email,password):authMod.signInWithEmailAndPassword(auth,email,password)}
 async function signOut(){return authMod.signOut(auth)}
 async function load(uid){const snap=await fsMod.getDoc(playerRef(uid));return snap.exists()?snap.data():null}
 async function save(game){const u=auth.currentUser;if(!u)return;await fsMod.setDoc(playerRef(u.uid),{...game,cloudUpdatedAt:Date.now()},{merge:false})}
 async function listings(){const q=fsMod.query(fsMod.collection(db,'v2MarketListings'),fsMod.where('status','==','active'),fsMod.orderBy('createdAt','desc'),fsMod.limit(100));return (await fsMod.getDocs(q)).docs.map(d=>({id:d.id,...d.data()}))}
 async function listItem(itemId,quantity,price){const u=auth.currentUser;if(!u)throw Error('Sign in to use the marketplace');const id=fsMod.doc(fsMod.collection(db,'v2MarketListings')).id;await fsMod.setDoc(listingRef(id),{sellerUid:u.uid,sellerName:u.displayName||u.email||'Adventurer',itemId,quantity,price,status:'active',credited:false,createdAt:Date.now()});return id}
 async function cancelListing(id){const u=auth.currentUser;if(!u)throw Error('Sign in');const ref=listingRef(id),me=playerRef(u.uid);return fsMod.runTransaction(db,async tx=>{const [ls,ps]=await Promise.all([tx.get(ref),tx.get(me)]);if(!ls.exists()||ls.data().sellerUid!==u.uid)throw Error('Not your listing');if(ls.data().status!=='active')throw Error('Listing is no longer active');if(!ps.exists())throw Error('Save your game first');const l=ls.data(),game=ps.data();game.inventory=game.inventory||{};game.inventory[l.itemId]=(game.inventory[l.itemId]||0)+l.quantity;tx.set(me,game);tx.update(ref,{status:'cancelled',cancelledAt:Date.now()});return {game,listing:{id,...l}}})}
 async function buyListing(id){const u=auth.currentUser;if(!u)throw Error('Sign in');const ref=listingRef(id),me=playerRef(u.uid);return fsMod.runTransaction(db,async tx=>{const [ls,ps]=await Promise.all([tx.get(ref),tx.get(me)]);if(!ls.exists()||ls.data().status!=='active')throw Error('Listing unavailable');if(!ps.exists())throw Error('Save your game first');const l=ls.data();if(l.sellerUid===u.uid)throw Error('Cannot buy your own listing');const game=ps.data();if((game.profile?.coins||0)<l.price)throw Error('Not enough coins');game.profile.coins-=l.price;game.inventory=game.inventory||{};game.inventory[l.itemId]=(game.inventory[l.itemId]||0)+l.quantity;tx.set(me,game);tx.update(ref,{status:'sold',buyerUid:u.uid,soldAt:Date.now(),credited:false});return {game,listing:{id,...l}}})}
 async function claimSales(){const u=auth.currentUser;if(!u)throw Error('Sign in');const q=fsMod.query(fsMod.collection(db,'v2MarketListings'),fsMod.where('sellerUid','==',u.uid),fsMod.limit(200));const candidates=(await fsMod.getDocs(q)).docs.filter(d=>d.data().status==='sold'&&!d.data().credited);if(!candidates.length)return {total:0,game:await load(u.uid)};const me=playerRef(u.uid);return fsMod.runTransaction(db,async tx=>{const playerSnap=await tx.get(me);if(!playerSnap.exists())throw Error('Save your game first');const fresh=[];for(const d of candidates){const snap=await tx.get(d.ref);if(snap.exists()&&snap.data().sellerUid===u.uid&&snap.data().status==='sold'&&!snap.data().credited)fresh.push({ref:d.ref,data:snap.data()})}const total=fresh.reduce((n,x)=>n+(x.data.price||0),0),game=playerSnap.data();game.profile.coins=(game.profile?.coins||0)+total;tx.set(me,game);for(const x of fresh)tx.update(x.ref,{credited:true,creditedAt:Date.now()});return {total,game}})}
 authMod.onAuthStateChanged(auth,u=>handlers.onAuth?.(u));
 return {auth,db,authMod,fsMod,signGoogle,signEmail,signOut,load,save,listings,listItem,cancelListing,buyListing,claimSales};
}
