import {ACTIONS,COOKING,RECIPES,ACTION_BY_ID,ENEMY_BY_ID,ITEMS,MAX_IDLE_MS,MAX_PET_WORKERS,levelFromXp,xpForLevel} from './data.js?v=2.1.2';
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const now=()=>Date.now();
export const copy=o=>structuredClone(o);
export function createState(name='Adventurer'){
 const skills={}; for(const id of ['woodcutting','mining','fishing','crafting','cooking','mischief','farm','hp','attack','defense','strength','ranged','magic']) skills[id]={xp:0};
 skills.hp.xp=xpForLevel(10);
 return {schema:2,profile:{name,coins:120,createdAt:now(),lastSeenAt:now(),avatar:'warrior'},skills,inventory:{'common-egg':1,'wood-axe':1,'wood-pickaxe':1,'wood-rod':1,'wood-dagger':1,'wood-arrows':50,'magic-essence':25,'wood-meal':8},equipment:{weapon:'wood-dagger',head:null,body:null,legs:null,trinket:null,tool:null,ammo:'wood-arrows'},activity:null,petJobs:[],pets:[],eggs:{},combat:null,combatPrefs:{style:'melee',enemyId:'moss-hare',autoEat:true,foodId:'wood-meal',petIds:[]},stats:{kills:0,eggs:0,hatched:0,crafted:0,actions:0,coinsEarned:0,highestHit:0},collection:{enemies:{},items:{}},market:{},mastery:{},farm:{petIds:[],food:0,lastTickAt:now(),produced:0}};
}
export function skillLevel(s,id){return levelFromXp(s.skills?.[id]?.xp||0)}
export function maxHp(s){return skillLevel(s,'hp')}
export function inv(s,id){return Number(s.inventory?.[id]||0)}
export function addItem(s,id,n){if(!n)return; s.inventory[id]=(s.inventory[id]||0)+n; if(s.inventory[id]<=0) delete s.inventory[id]; if(n>0)s.collection.items[id]=true;}
export function canRun(s,a){if(!a)return false; const skill=a.skill||'crafting'; if(skillLevel(s,skill)<(a.level||1))return false; return Object.entries(a.inputs||{}).every(([id,n])=>inv(s,id)>=n)}
export function actionDuration(s,a,pet=null){let ms=(a.duration||6)*1000; const tool=s.equipment.tool&&ITEMS[s.equipment.tool]; if(!pet && tool?.skill===a.skill) ms*=1-(tool.speedBonus||0); if(pet){const favored=(pet.workSkills||[]).includes(a.skill);const b=(pet.workBonus||0)*(favored?1:.5)+Math.floor((pet.level||1)/10);ms*=1-b/100;} return Math.max(1200,ms)}
export function startActivity(s,actionId,at=now()){const a=ACTION_BY_ID[actionId]; if(!a)throw Error('Unknown action'); if(skillLevel(s,a.skill||'crafting')<(a.level||1))throw Error(`${a.skill||'Crafting'} level ${a.level||1} required`); if(a.inputs&&!canRun(s,a))throw Error('Missing materials'); s.activity={actionId,startedAt:at,cycleStartedAt:at,completed:0}; s.combat=null; return s;}
export function stopActivity(s){s.activity=null; return s}
export function assignPet(s,petId,actionId,at=now()){if(s.petJobs.length>=MAX_PET_WORKERS)throw Error('Only two pets can work at once'); if(s.petJobs.some(j=>j.petId===petId))throw Error('That pet is already working'); if(s.combatPrefs.petIds.includes(petId))throw Error('Remove that pet from your combat party first'); const pet=s.pets.find(p=>p.id===petId); if(!pet)throw Error('Pet not found'); const a=ACTION_BY_ID[actionId]; if(!a||['hp','attack','defense','strength','ranged','magic'].includes(a.skill))throw Error('Pets cannot do that'); if(skillLevel(s,a.skill||'crafting')<(a.level||1))throw Error(`${a.skill||'Crafting'} level ${a.level||1} required`); s.petJobs.push({petId,actionId,startedAt:at,cycleStartedAt:at,completed:0}); return s}
export function stopPet(s,petId){s.petJobs=s.petJobs.filter(j=>j.petId!==petId); return s}
function grantAction(s,a,pet=null,rng=Math.random){if(a.inputs)for(const [id,n] of Object.entries(a.inputs))addItem(s,id,-n); for(const [id,n] of Object.entries(a.rewards||a.outputs||{})){let qty=n; if(pet && rng()<Math.min(.25,(pet.workBonus||0)/200))qty+=n; addItem(s,id,qty)} s.profile.coins+=(a.coins||0); s.skills[a.skill||'crafting'].xp+=(a.xp||10); if(pet){pet.xp=(pet.xp||0)+Math.max(2,Math.floor((a.xp||10)*.65));pet.level=levelFromXp(pet.xp);} s.mastery[a.id]=(s.mastery[a.id]||0)+1; s.stats.actions++; if(a.skill==='crafting')s.stats.crafted++;}
function settleJob(s,job,at,pet,rng){const a=ACTION_BY_ID[job.actionId]; if(!a)return null; let cursor=job.cycleStartedAt||job.startedAt,blocked=false,loops=0; while(loops<100000){const dur=actionDuration(s,a,pet); if(cursor+dur>at)break; if(a.inputs&&!canRun(s,a)){blocked=true;break;} grantAction(s,a,pet,rng); cursor+=dur; job.completed++; loops++;} job.cycleStartedAt=blocked?at:cursor; return job}
export function settleActivities(s,at=now(),rng=Math.random){const capped=Math.min(at,(s.profile.lastSeenAt||at)+MAX_IDLE_MS); if(s.activity){const j=settleJob(s,s.activity,capped,null,rng); if(!j)s.activity=null;} s.petJobs=s.petJobs.map(j=>settleJob(s,j,capped,s.pets.find(p=>p.id===j.petId),rng)).filter(Boolean); s.profile.lastSeenAt=at; return s}
export function hatchCommonEgg(s,rng=Math.random){if(inv(s,'common-egg')<1)throw Error('No Common Egg to hatch');const pool=Object.values(ENEMY_BY_ID).filter(e=>e.rarity==='Common');if(!pool.length)throw Error('No common creatures configured');addItem(s,'common-egg',-1);const e=pool[Math.floor(rng()*pool.length)];const pet={id:`pet-${e.id}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,speciesId:e.id,level:1,xp:0,nickname:null,name:e.name,workSkills:e.workSkills,workBonus:e.workBonus,combatBonus:e.combatBonus};s.pets.push(pet);s.stats.hatched++;return pet}
export function addPetToFarm(s,petId){s.farm=s.farm||{petIds:[],food:0,lastTickAt:now(),produced:0};if(s.farm.petIds.includes(petId))throw Error('Already on the farm');const pet=s.pets.find(p=>p.id===petId);if(!pet)throw Error('Pet not found');const copies=s.pets.filter(p=>p.speciesId===pet.speciesId);const activeCopy=copies.some(p=>p.id!==petId&&!s.farm.petIds.includes(p.id));if(!activeCopy)throw Error('Keep one companion copy before farming a duplicate');if(s.petJobs.some(j=>j.petId===petId)||s.combatPrefs.petIds.includes(petId))throw Error('This pet is busy');s.farm.petIds.push(petId);return s}
export function removePetFromFarm(s,petId){s.farm.petIds=(s.farm?.petIds||[]).filter(id=>id!==petId);return s}
export function feedFarm(s,itemId,qty=1){const it=ITEMS[itemId];if(!it?.heal||inv(s,itemId)<qty)throw Error('You need edible food');addItem(s,itemId,-qty);s.farm.food=Math.min(9999,(s.farm.food||0)+qty*Math.max(1,it.heal));return s}
export function settleFarm(s,at=now()){s.farm=s.farm||{petIds:[],food:0,lastTickAt:at,produced:0};const cap=Math.min(at,(s.farm.lastTickAt||at)+MAX_IDLE_MS);let cursor=s.farm.lastTickAt||cap;const interval=300000;while(cursor+interval<=cap&&s.farm.food>0&&s.farm.petIds.length){for(const pid of [...s.farm.petIds]){if(s.farm.food<=0)break;const pet=s.pets.find(p=>p.id===pid),e=pet&&ENEMY_BY_ID[pet.speciesId];if(!e)continue;const drop=(e.drops||[])[0];if(drop)addItem(s,drop.item,1);else s.profile.coins+=2;s.farm.food--;s.skills.farm.xp+=8+Math.floor(e.level/2);s.farm.produced++;}cursor+=interval;}s.farm.lastTickAt=cap;return s}
export function hatchEgg(s,speciesId){const id='egg-'+speciesId;if(inv(s,id)<1)throw Error('No egg to hatch'); addItem(s,id,-1); const pet={id:`pet-${speciesId}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,speciesId,level:1,xp:0,nickname:null}; const e=ENEMY_BY_ID[speciesId]; pet.name=e.name; pet.workSkills=e.workSkills; pet.workBonus=e.workBonus; pet.combatBonus=e.combatBonus; s.pets.push(pet); s.stats.hatched++; return pet}
export function combatStats(s,style=s.combatPrefs.style,enemyId=s.combatPrefs.enemyId){const enemy=ENEMY_BY_ID[enemyId]; const weapon=ITEMS[s.equipment.weapon]||{}; const attackSkill=style==='melee'?'attack':style; const lvl=skillLevel(s,attackSkill), def=skillLevel(s,'defense'), str=skillLevel(s,'strength'); const stylePower=style==='melee'?str:(style==='ranged'?skillLevel(s,'ranged'):skillLevel(s,'magic')); const companions=(s.combatPrefs.petIds||[]).map(id=>s.pets.find(p=>p.id===id)).filter(Boolean); const support=companions.reduce((n,p)=>n+(p.combatBonus||0),0); const gearAcc=(weapon.style===style?(weapon.attack||0):0)+Object.values(s.equipment).reduce((n,id)=>n+(ITEMS[id]?.accuracy||0),0); const accuracy=lvl*1.6+gearAcc*2+8+support*.22; const enemyAvoid=enemy.defense*2.2+enemy.level*.35; let hitChance=clamp(accuracy/(accuracy+enemyAvoid),.12,.96); if(enemy.strongAgainst===style)hitChance*=.82;if(enemy.weakTo===style)hitChance=Math.min(.98,hitChance*1.12); const ammo=style==='ranged'?ITEMS[s.equipment.ammo]:null; const ammoPower=ammo?.tier||0; const weaponPower=style==='melee'?(weapon.strength||2):(style==='ranged'?(weapon.ranged||2)+ammoPower*.35:(weapon.magic||2)); let maxHit=Math.max(1,Math.floor(1+stylePower/6+weaponPower*.55+support/12)); if(enemy.strongAgainst===style)maxHit=Math.floor(maxHit*.72); if(enemy.weakTo===style)maxHit=Math.ceil(maxHit*1.18); maxHit=Math.min(45,maxHit); const critChance=clamp(.03+Object.values(s.equipment).reduce((n,id)=>n+(ITEMS[id]?.crit||0),0)/100+support/2000,.03,.20); const speedMs=weapon.style===style?(weapon.speedMs||3000):3600; return {hitChance,critChance,maxHit,speedMs,defense:def,support,companions};}
export function startCombat(s,enemyId,style='melee',at=now()){const enemy=ENEMY_BY_ID[enemyId]; if(!enemy)throw Error('Enemy not found');const weapon=ITEMS[s.equipment.weapon]||{};if(weapon.style!==style)throw Error(`Equip a ${style} weapon first`);if(style==='ranged'&&(!s.equipment.ammo||inv(s,s.equipment.ammo)<1))throw Error('Equip arrows first');if(style==='magic'&&inv(s,'magic-essence')<(weapon.essenceCost||1))throw Error('You need Magic Essence'); s.activity=null; s.combatPrefs.enemyId=enemyId;s.combatPrefs.style=style; const hp=maxHp(s); s.combat={enemyId,style,startedAt:at,playerHp:hp,enemyHp:enemy.hp,playerNextAt:at+combatStats(s,style,enemyId).speedMs,enemyNextAt:at+enemy.speedMs,killsThisSession:0,lastEvents:[]}; return s}
export function stopCombat(s){s.combat=null;return s}
function log(c,text,type='info',amount=0,side=''){c.lastEvents.unshift({id:Math.random().toString(36).slice(2),at:Date.now(),text,type,amount,side});c.lastEvents=c.lastEvents.slice(0,18)}
function consumeAmmo(s,style){const w=ITEMS[s.equipment.weapon]||{}; if(style==='ranged'){const ammo=s.equipment.ammo;if(!ammo||inv(s,ammo)<=0)return false;addItem(s,ammo,-1)} if(style==='magic'){const cost=w.essenceCost||1;if(inv(s,'magic-essence')<cost)return false;addItem(s,'magic-essence',-cost)} return true}
function rewardKill(s,c,enemy,rng){s.stats.kills++;c.killsThisSession++;s.collection.enemies[enemy.id]=(s.collection.enemies[enemy.id]||0)+1;const [a,b]=enemy.coinDrop;const coins=a+Math.floor(rng()*(b-a+1));s.profile.coins+=coins;s.stats.coinsEarned+=coins;for(const d of enemy.drops||[])if(rng()<d.chance)addItem(s,d.item,d.min+Math.floor(rng()*(d.max-d.min+1)));if(rng()<1/enemy.eggRate){addItem(s,'egg-'+enemy.id,1);s.stats.eggs++;log(c,`RARE DROP! ${enemy.name} Egg (1/${enemy.eggRate})`,'rare')} const style=c.style;if(style==='melee'){s.skills.attack.xp+=enemy.level*2+8;s.skills.strength.xp+=enemy.level*2+8}else s.skills[style].xp+=enemy.level*3+12;s.skills.defense.xp+=enemy.level+5;s.skills.hp.xp+=enemy.level+5;for(const id of s.combatPrefs.petIds||[]){const p=s.pets.find(x=>x.id===id);if(p){p.xp=(p.xp||0)+enemy.level+8;p.level=levelFromXp(p.xp);}} log(c,`Defeated ${enemy.name} · +${coins} coins`,'kill'); c.enemyHp=enemy.hp;}
export function combatTick(s,at=now(),rng=Math.random){const c=s.combat;if(!c)return s;const enemy=ENEMY_BY_ID[c.enemyId];let guard=0;while(guard++<100000 && (c.playerNextAt<=at||c.enemyNextAt<=at)){
 if(c.playerNextAt<=c.enemyNextAt){const st=combatStats(s,c.style,c.enemyId); if(!consumeAmmo(s,c.style)){log(c,c.style==='ranged'?'Out of arrows!':'Out of Magic Essence!','warning'); c.playerNextAt=at+1000; break;} if(rng()<st.hitChance){let dmg=1+Math.floor(rng()*st.maxHit);const crit=rng()<st.critChance;if(crit)dmg=Math.min(65,Math.max(dmg+2,Math.floor(dmg*1.6)));c.enemyHp=Math.max(0,c.enemyHp-dmg);s.stats.highestHit=Math.max(s.stats.highestHit,dmg);log(c,crit?`Critical ${dmg}!`:`You hit ${dmg}.`,crit?'crit':'hit',dmg,'enemy')}else log(c,'You miss.','miss',0,'enemy'); if(c.enemyHp>0){for(const pet of st.companions){if(rng()<.24){const petMax=Math.max(1,Math.min(8,1+Math.floor((pet.combatBonus||1)/2)));const pd=1+Math.floor(rng()*petMax);c.enemyHp=Math.max(0,c.enemyHp-pd);log(c,`${pet.name} assists for ${pd}.`,'pet',pd,'enemy');if(c.enemyHp<=0)break;}}} c.playerNextAt+=st.speedMs;if(c.enemyHp<=0){rewardKill(s,c,enemy,rng);c.playerNextAt=Math.max(c.playerNextAt,c.enemyNextAt+500);}}
 else {const avoid=8+skillLevel(s,'defense')*1.8+Object.values(s.equipment).reduce((n,id)=>n+(ITEMS[id]?.defense||0),0)*2;const chance=clamp((enemy.attack*2+enemy.level*.4)/(enemy.attack*2+enemy.level*.4+avoid),.1,.88);if(rng()<chance){const dmg=1+Math.floor(rng()*enemy.maxHit);c.playerHp=Math.max(0,c.playerHp-dmg);log(c,`${enemy.name} hits ${dmg}.`,'hurt',dmg,'player')}else log(c,`${enemy.name} misses.`,'miss');c.enemyNextAt+=enemy.speedMs;if(c.playerHp<=0){log(c,'You were defeated. Combat stopped.','defeat');s.combat=null;break;}}
 if(s.combat && s.combatPrefs.autoEat && c.playerHp>0 && c.playerHp<maxHp(s)*.35){const f=ITEMS[s.combatPrefs.foodId];if(f?.heal&&inv(s,s.combatPrefs.foodId)>0){addItem(s,s.combatPrefs.foodId,-1);c.playerHp=Math.min(maxHp(s),c.playerHp+f.heal);log(c,`Auto-ate ${f.name} +${f.heal} HP`,'heal',f.heal,'player')}}
 }
 s.profile.lastSeenAt=at;return s}
export function settleOfflineCombat(s,at=now(),rng=Math.random){if(!s.combat)return s;const cap=Math.min(at,(s.profile.lastSeenAt||at)+MAX_IDLE_MS);combatTick(s,cap,rng);s.profile.lastSeenAt=at;return s}
export function buyShop(s,itemId,quantity=1,totalCost=1){const cost=totalCost;if(s.profile.coins<cost)throw Error('Not enough coins');s.profile.coins-=cost;addItem(s,itemId,quantity);return s}
export function equip(s,itemId){const it=ITEMS[itemId];if(!it||inv(s,itemId)<1)throw Error('Item not owned');const req=Math.max(1,1+(Number(it.tier||1)-1)*10);if(it.category==='weapon'){const skill=it.style==='melee'?'attack':it.style;if(skillLevel(s,skill)<req)throw Error(`${skill} level ${req} required`);s.equipment.weapon=itemId}else if(it.category==='armor'){const skill=it.style==='ranged'?'ranged':it.style==='magic'?'magic':'defense';if(skillLevel(s,skill)<req)throw Error(`${skill} level ${req} required`);s.equipment[it.slot]=itemId}else if(it.category==='trinket')s.equipment[it.slot]=itemId;else if(it.category==='tool'){if(skillLevel(s,it.skill)<req)throw Error(`${it.skill} level ${req} required`);s.equipment.tool=itemId}else if(it.category==='ammo'){if(skillLevel(s,'ranged')<req)throw Error(`ranged level ${req} required`);s.equipment.ammo=itemId}else throw Error('Not equippable');return s}
export function eat(s,itemId){const it=ITEMS[itemId];if(!it?.heal||inv(s,itemId)<1)throw Error('Not edible');addItem(s,itemId,-1);if(s.combat)s.combat.playerHp=Math.min(maxHp(s),s.combat.playerHp+it.heal);return s}
export function normalizeState(raw,name='Adventurer'){const base=createState(name);if(!raw||raw.schema!==2)return base;return {...base,...raw,profile:{...base.profile,...raw.profile},skills:{...base.skills,...raw.skills},inventory:{...raw.inventory},equipment:{...base.equipment,...raw.equipment},combatPrefs:{...base.combatPrefs,...raw.combatPrefs},stats:{...base.stats,...raw.stats},collection:{enemies:{...(raw.collection?.enemies||{})},items:{...(raw.collection?.items||{})}},mastery:{...(raw.mastery||{})},pets:[...(raw.pets||[])],petJobs:[...(raw.petJobs||[])],farm:{...base.farm,...(raw.farm||{})}};}
